#!/bin/bash
set -exu -o pipefail

# shellcheck source=common.sh
. /usr/libexec/gluster-container/common.sh

usage() {
    cat <<EOF
SYNOPSIS
       $0 [-p GLUSTER_POOL] [-v GLUSTER_VG]

Mount all volumes in the gluster thin pool GLUSTER_POOL in volume group 
GLUSTER_VG to /brick/BRICKNAME to be used by GlusterFS.
EOF
}

copy_default_if_not_exists() {
    if [ ! "$(ls -A "$1")" ]; then
        cp --reflink=auto -a "${1}_default/* $1"
    fi
}

validate_env() {
    test_var GLUSTER_VG
    test_var GLUSTER_POOL
    if ! vg_exists "$GLUSTER_VG" ; then
        err "Volume group $GLUSTER_VG does not exist or is not mounted in /dev/$GLUSTER_VG"
    fi
}

create_vg_if_not_exists() {
    test_var GLUSTER_VG
    if vg_exists "$GLUSTER_VG"; then
        return 0
    fi

    test_var GLUSTER_PV
    # shellcheck disable=SC2153
    chroot_host vgcreate "$GLUSTER_VG" "$GLUSTER_PV"
}

create_pool_if_not_exists() {
    if pool_exists "$GLUSTER_VG/$GLUSTER_POOL"; then
        return 0
    fi

    test_var GLUSTER_POOL_INITIAL_SIZE
 
    if [[ "$GLUSTER_POOL_INITIAL_SIZE" == *%* ]]; then
        chroot_host lvcreate -l "$GLUSTER_POOL_INITIAL_SIZE" --type thin-pool \
                 --thinpool "$GLUSTER_POOL" "${GLUSTER_VG}"
    else
        chroot_host lvcreate -L "$GLUSTER_POOL_INITIAL_SIZE" --type thin-pool \
                 --thinpool "$GLUSTER_POOL" "${GLUSTER_VG}"
    fi
    # TODO: enable auto pool extension
}

main() {
  while getopts "p:v:u" flag
  do
    case "$flag" in
      p)
        if [ -z "$OPTARG" ]; then
          err "Missing argument GLUSTER_POOL for -p"
          exit 1
        fi
        GLUSTER_POOL="$OPTARG"
        ;;
      v)
        if [ -z "$OPTARG" ]; then
          err "Missing argument GLUSTER_VG for -p"
          exit 1
        fi
        GLUSTER_VG="$OPTARG"
        ;;
      u)
        usage
        exit 0
        ;;
      *)
        err "invalid option: $flag"
        exit 1
        ;;
    esac
  done

  copy_default_if_not_exists /etc/glusterfs
  copy_default_if_not_exists /var/lib/glusterd
  validate_env
  create_vg_if_not_exists
  create_pool_if_not_exists
  mount_bricks
}

main
